### ISSUE TITLE
Unable to use facebook or twitter in any version of showcase

### ISSUE THREAD

**Issue by mikedeanklein** [spring-projects/spring-social-samples#70]
I've tried several versions. All I've done is update the clientId and clientSecret for my own facebook and twitter app.

The facebook error I receive is:
Not Logged In: You are not logged in. Please login and try again.

By building off of later versions of spring boot (1.5.x) I'm able to get past this but then hit an issue with "bio" field being deprecated and the getUserProfile call fails due to this.

The twitter error I receive is:
org.springframework.web.client.ResourceAccessException: I/O error on POST request for "https://api.twitter.com/oauth/request_token": cannot retry due to server authentication, in streaming mode; nested exception is java.net.HttpRetryException: cannot retry due to server authentication, in streaming mode
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:607) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]

**Comment by mikedeanklein** [comment]
Seem to be having more success with OAuth2 pattern in Dave's SSO example. Workarounds I've seen to get past bio field issue have unfortunate side affect of ret'g no results when calling getUserProfile. The other failure was due to a trailing space character in my client properties secret...love whitespace errors. There's so little code in the different providers it shouldnt' present a problem if I actually did have to change something anyways.
